# Generated by Django 3.2.8 on 2021-12-21 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='profile id')),
                ('profile_tin', models.PositiveIntegerField(verbose_name='Taxpayer Identification Number')),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('tax_country', models.CharField(max_length=80, verbose_name='Tax country')),
                ('tax_state', models.CharField(blank=True, max_length=80, verbose_name='Tax State (tax state for US persons only)')),
                ('address', models.CharField(max_length=255, verbose_name='Address (Street address, City, State/Region, Country, Postal Code)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='The User Profile')),
            ],
            options={
                'verbose_name': 'Alfred Profile',
                'verbose_name_plural': 'Alfred Profiles',
            },
        ),
    ]
