# Generated by Django 3.2.8 on 2021-12-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_rename_user_profile_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_tin',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Taxpayer Identification Number'),
        ),
    ]
