# Generated by Django 3.2.8 on 2021-12-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_alter_profile_profile_tin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default='2000-01-01', verbose_name='Date of Birth'),
        ),
    ]
