# Generated by Django 3.2.8 on 2021-12-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0006_profile_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance_btc',
            field=models.PositiveIntegerField(default=2.096, verbose_name='Balance in BitCoin'),
        ),
        migrations.AddField(
            model_name='profile',
            name='balance_usd',
            field=models.PositiveIntegerField(default=100000, verbose_name='Balance in USD/$'),
        ),
    ]
