# Generated by Django 3.2.8 on 2021-12-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0007_auto_20211228_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance_btc',
            field=models.FloatField(default=2.096, verbose_name='Balance in BitCoin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance_usd',
            field=models.FloatField(default=100000.0, verbose_name='Balance in USD/$'),
        ),
    ]
