# Generated by Django 3.2.8 on 2021-12-20 17:56

import core.polaris.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=255)),
                ('issuer', models.TextField(validators=[django.core.validators.MinLengthValidator(56)])),
                ('significant_decimals', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('deposit_enabled', models.BooleanField(default=True)),
                ('deposit_fee_fixed', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True)),
                ('deposit_fee_percent', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deposit_min_amount', models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=30)),
                ('deposit_max_amount', models.DecimalField(blank=True, decimal_places=7, default=999999999999999999, max_digits=30)),
                ('withdrawal_enabled', models.BooleanField(default=True)),
                ('withdrawal_fee_fixed', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True)),
                ('withdrawal_fee_percent', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('withdrawal_min_amount', models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=30)),
                ('withdrawal_max_amount', models.DecimalField(blank=True, decimal_places=7, default=999999999999999999, max_digits=30)),
                ('send_fee_fixed', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True)),
                ('send_fee_percent', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('send_min_amount', models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=30)),
                ('send_max_amount', models.DecimalField(blank=True, decimal_places=7, default=999999999999999999, max_digits=30)),
                ('distribution_seed', core.polaris.models.EncryptedTextField(blank=True, null=True)),
                ('sep24_enabled', models.BooleanField(default=False)),
                ('sep6_enabled', models.BooleanField(default=False)),
                ('sep31_enabled', models.BooleanField(default=False)),
                ('sep38_enabled', models.BooleanField(default=False)),
                ('symbol', models.TextField(default='$')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_asset', models.CharField(max_length=255)),
                ('sell_asset', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stellar_account', models.CharField(max_length=255)),
                ('account_memo', models.PositiveIntegerField(blank=True, null=True)),
                ('muxed_account', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('firm', 'firm'), ('indicative', 'indicative')], max_length=80)),
                ('sell_asset', models.CharField(max_length=255)),
                ('buy_asset', models.CharField(max_length=255)),
                ('sell_amount', models.DecimalField(decimal_places=7, max_digits=30)),
                ('buy_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('country_code', models.TextField(blank=True, null=True)),
                ('requested_expire_after', models.DateTimeField(blank=True, null=True)),
                ('buy_delivery_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polaris.deliverymethod')),
                ('sell_delivery_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polaris.deliverymethod')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('paging_token', models.TextField(blank=True, null=True)),
                ('stellar_account', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('muxed_account', models.TextField(blank=True, null=True)),
                ('account_memo', models.PositiveIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal'), ('send', 'send'), ('deposit-exchange', 'deposit-exchange'), ('withdrawal-exchange', 'withdrawal-exchange')], default='deposit', max_length=20)),
                ('status', models.CharField(choices=[('pending_anchor', 'pending_anchor'), ('pending_trust', 'pending_trust'), ('pending_user', 'pending_user'), ('pending_user_transfer_start', 'pending_user_transfer_start'), ('incomplete', 'incomplete'), ('no_market', 'no_market'), ('too_small', 'too_small'), ('too_large', 'too_large'), ('pending_sender', 'pending_sender'), ('pending_receiver', 'pending_receiver'), ('pending_transaction_info_update', 'pending_transaction_info_update'), ('pending_customer_info_update', 'pending_customer_info_update'), ('completed', 'completed'), ('error', 'error'), ('pending_external', 'pending_external'), ('pending_stellar', 'pending_stellar')], default='pending_external', max_length=31)),
                ('status_eta', models.IntegerField(blank=True, null=True)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('stellar_transaction_id', models.TextField(blank=True, null=True)),
                ('external_transaction_id', models.TextField(blank=True, null=True)),
                ('amount_in', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True)),
                ('amount_expected', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True)),
                ('amount_out', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True)),
                ('amount_fee', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True)),
                ('fee_asset', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=core.polaris.models.utc_now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('from_address', models.TextField(blank=True, null=True)),
                ('to_address', models.TextField(blank=True, null=True)),
                ('required_info_updates', models.TextField(blank=True, null=True)),
                ('required_info_message', models.TextField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('memo_type', models.CharField(choices=[('text', 'text'), ('id', 'id'), ('hash', 'hash')], default='text', max_length=10)),
                ('receiving_anchor_account', models.TextField(blank=True, null=True)),
                ('refunded', models.BooleanField(default=False)),
                ('protocol', models.CharField(blank=True, choices=[('sep6', 'sep6'), ('sep24', 'sep24'), ('sep31', 'sep31')], max_length=5, null=True)),
                ('pending_signatures', models.BooleanField(default=False)),
                ('envelope_xdr', models.TextField(blank=True, null=True, validators=[core.polaris.models.deserialize])),
                ('channel_seed', core.polaris.models.EncryptedTextField(blank=True, null=True)),
                ('claimable_balance_supported', models.BooleanField(default=False)),
                ('claimable_balance_id', models.TextField(blank=True, null=True)),
                ('more_info_url', models.TextField(blank=True, null=True)),
                ('on_change_callback', models.TextField(blank=True, null=True)),
                ('pending_execution_attempt', models.BooleanField(default=False)),
                ('client_domain', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polaris.asset')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polaris.quote')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='OffChainAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('significant_decimals', models.PositiveIntegerField(default=2)),
                ('country_codes', models.TextField(blank=True, null=True)),
                ('symbol', models.TextField(blank=True, null=True)),
                ('delivery_methods', models.ManyToManyField(to='polaris.DeliveryMethod')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exchangepair',
            constraint=models.UniqueConstraint(fields=('buy_asset', 'sell_asset'), name='exchangepair_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='deliverymethod',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='deliverymethod_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='offchainasset',
            constraint=models.UniqueConstraint(fields=('scheme', 'identifier'), name='offchain_unique_index'),
        ),
    ]
